### ISSUE TITLE
Error starting the container

### ISSUE THREAD

**Issue by chrisp250** [teknofile/docker-cacti#4]
The container exists straight away with the error message:
standard_init_linux.go:211: exec user process caused "exec format error"

I'm trying to run in on an Odroid N2 (ARM based).
Thank you

**Comment by teknofile** [comment]
Well, that's interesting. What processor is in  the Odroid N2? I'm not familiar with it. What digest/hash is being pulled? I know I've build arm64/arm v7 (32bit) and amd64 versions of the container. 

The exec format error Ive only seen when running a container for one arch on a diff arch.

**Comment by chrisp250** [comment]
Thanks for getting back to me.

The processor is an ARMv8. This is the [manufacturer's page](https://www.hardkernel.com/shop/odroid-n2-with-4gbyte-ram/)

Hash/digest, is this what you mean? sha256:52549d468e2e25c0a160dc712ca7d692c002b7dcf2f4302234569fd9bd6f814d

Also it says:

_Created: 2020-04-23 09:46:42
Build: Docker  on linux, arm64_

Hope that helps.
Christian

**Comment by teknofile** [comment]
No worries. Let me look at building it for armv8. I think I can emulate it. Appreciate you looking at the container and would like to make it work for you.

**Comment by chrisp250** [comment]
Thanks mate. 
I'm far from a Docker expect. Not sure how it decides which image to pull based on the architecture. I would have expecected that if there was no matching image it would give me an error rather than still pull it and try to run it.
Let me know if I can help with anything.
Christian

**Comment by teknofile** [comment]
After investingating today, pretty sure this is due to the hard coded pulling in of the amd64 s6-overlay. I fixed this in another container I was using a month or two ago and will patch that in shortly (hopefully this evening).

**Comment by chrisp250** [comment]
No worries. Thank you for the heads up.

**Comment by teknofile** [comment]
@chrisp250 - can you check out the image: teknofile/tkf-docker-cacti:arm64-test

I've done some initial functional basic tests but haven't gone to the extent of setting up cacti and all. The image does run on AWS a1 instaces

**Comment by chrisp250** [comment]
Hi James,
It looks like it's working now...

`
** Making our folders
** Copy default configurations into /config
cp: cannot stat '/defaults/www2.conf': No such file or directory
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Can't load /root/.rnd into RNG
547716650624:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
Generating a RSA private key
.................................................................................................................................................+++++
......................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-install: executing... 
[cont-init.d] 50-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Created directory: /var/lib/snmp/mib_indexes
`

Thank you for working on it.
Christian
